# Search , Sort , Search Sorted , Filter

Search Array:- Search an array for a certain value, and return the indexes that 
get a match

## search

In [11]:
import numpy as np
var =  np.array([4,2,3,4,2,5,2,5,7,6,7])
# index          0,1,2,3,4,5,6,7,8,9,10
s = np.where(var == 2) # where is a function which returns the index of the element 
s1 = np.where((var%2) == 0) # elements which are divisble by 2
print(s)
print(s1)

(array([1, 4, 6], dtype=int64),)
(array([0, 1, 3, 4, 6, 9], dtype=int64),)


## Search Sorted Array

search sorted array:- which performs a binary search in the array , and returns the index where the specified value would be inserted to maintain the search order.

In [26]:
import numpy as np
var1 =  np.array([4,2,3,4,6,7,8,9,10])
# index          0,1,2,3,4,5,6,7,8,9

s2 = np.searchsorted(var1 , 5) 
print(s2) # gives the index where the element can be placed


4


In [36]:
import numpy as np
var1 =  np.array([4,2,3,4,9,10])
# index          0,1,2,3,4,5

s2 = np.searchsorted(var1 , [5,6,7],side='right') 
print(s2) # gives the index where the element can be placed from right side


[4 4 4]


## Sort Array

 Sort Array :- Ordered sequence is any sequence that has an order corresponding to elements , like numeric or alphabetical, ascending or descending.

In [40]:
var_1 =  np.array([4,2,3,4,12,5,22,5,7])
# index          0,1,2,3,4,5,6,7,8,9,10 
print(np.sort(var_1))

[ 2  3  4  4  5  5  7 12 22]


In [49]:
var_2 =  np.array(['a','s','d','f'])
print(np.sort(var_2))

['a' 'd' 'f' 's']


## Filter Array

Filter Array:- Getting some elements out of an existing array and creating a new array out of them.

In [51]:
var_3 =  np.array(['a','s','d','f'])

f = [True,False,False,True]
new_arr = var_3[f]
print("Filtered array:- ",new_arr)
print('Type:- ',type(new_arr))

Filtered array:-  ['a' 'f']
Type:-  <class 'numpy.ndarray'>
