# Functions In NumPy

## Arithmetic Functions
- Shuffle
- Unique
- Resize
- Flatten
- Ravel

## Shuffle

In [4]:
import numpy as np
var = np.array([1,2,3,4,5])
print('Before Shuffling :- ',var)
np.random.shuffle(var)
print('After Shuffling :- ',var)

Before Shuffling :-  [1 2 3 4 5]
After Shuffling :-  [5 1 2 4 3]


## Unique

In [18]:
var1 = np.array([1,2,3,4,2,5,2,6,7])
print('var1 :- ',var1)
x = np.unique(var1)
y = np.unique(var1,return_index=True,return_counts=True)
print('Unique values :- ',x)
print('Index values :- \n',y)

var1 :-  [1 2 3 4 2 5 2 6 7]
Unique values :-  [1 2 3 4 5 6 7]
Index values :- 
 (array([1, 2, 3, 4, 5, 6, 7]), array([0, 1, 2, 3, 5, 7, 8], dtype=int64), array([1, 3, 1, 1, 1, 1, 1], dtype=int64))


## Resize

In [23]:
var2 = np.array([1,2,3,4,5,6])
print('Before',var2)
y = np.resize(var2,(2,3))
print('resize\n',y)

Before [1 2 3 4 5 6]
resize
 [[1 2 3]
 [4 5 6]]


## Flatten  and Ravel 
- Converts 2-D array into 1-D array
-  order : {'C','F','A','K'},Optional
- 'C' means to flatten in row-major (C-style) order
- 'F' means to flatten in column-major(Fortan-style)order
- 'A' means to flatten in column-major order if 'a' is Fortan *contiguous* in memory ,row-major order otherwise
- 'K' means to flatten 'a' in the order the elements occur in memory
- The default is 'C'

In [54]:
var2 = np.array([1,2,3,4,5,6])

y = np.resize(var2,(3,2))
print('Output of y\n',y)
print()
print('Flatten output:-',y.flatten())
print()
print('Flatten order output:-',y.flatten(order='F')) # change the order
print()
print('Ravel',np.ravel(y,order='F'))

Output of y
 [[1 2]
 [3 4]
 [5 6]]

Flatten output:- [1 2 3 4 5 6]

Flatten order output:- [1 3 5 2 4 6]

Ravel [1 3 5 2 4 6]


# Insert and Delete Functions

## Insert

In [65]:
import numpy as np
var = np.array([1,2,3,4,5])
print('var:- ',var)
v = np.insert(var , (2 ,4), 40) # array in which u want to insert,position,value
# it will not accept float value accepts only integer
print(v)

var:-  [1 2 3 4 5]
[ 1  2 40  3  4 40  5]


In [97]:
var1 = np.array([[1,2,3],[1,2,3]])
v1 = np.insert(var1 , 2 , 6, axis=1)
v2 = np.insert(var1 , 2 , 6, axis=0)
v3 = np.insert(var1 , 2,[22,23] , axis=1)

print('v1 \n',v1)
print()
print('v2 \n',v2)
print()
print('v3 \n',v3)


v1 
 [[1 2 6 3]
 [1 2 6 3]]

v2 
 [[1 2 3]
 [1 2 3]
 [6 6 6]]

v3 
 [[ 1  2 22  3]
 [ 1  2 23  3]]


In [109]:
var1 = np.array([[1,2,3],[1,2,3]])
print('var \n',var1)
print('\nInserted \n')
x=np.append(var1,[[45,44,23]],axis=0)
print(x)

var 
 [[1 2 3]
 [1 2 3]]

Inserted 

[[ 1  2  3]
 [ 1  2  3]
 [45 44 23]]


## Delete 

In [112]:
import numpy as np
var = np.array([1,2,3,4,5])
print('var:- ',var)
d = np.delete(var,2)
print('After deleting:- ',d)

var:-  [1 2 3 4 5]
After deleting:-  [1 2 4 5]
