# Broadcasting in NumPy

In [5]:
import numpy as np
var1=np.array([1,2,3,4])
var2=np.array([1,2,3,])
print(var1+var2)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [23]:
import numpy as np
var1=np.array([1,2,3])
print('Shpae: ',var1.shape)
print()
print('var1: ',var1)
print()

var2=np.array([[1],[2],[3]])
print('Shape: \n',var2.shape)
print()
print('var2: \n',var2)
print()

print('Addition:\n',var1+var2)

Shpae:  (3,)

var1:  [1 2 3]

Shape: 
 (3, 1)

var2: 
 [[1]
 [2]
 [3]]

Addition:
 [[2 3 4]
 [3 4 5]
 [4 5 6]]


In [35]:
x=np.array([[1],[2]])
print(x)
print('Shape: ',x.shape)
print()

y=np.array([[1,2,3],[1,2,3]])
print(y)
print('Shape: ',y.shape)
print()

print('addition:\n',x+y)

[[1]
 [2]]
Shape:  (2, 1)

[[1 2 3]
 [1 2 3]]
Shape:  (2, 3)

addition:
 [[2 3 4]
 [3 4 5]]
