# Indexing and Slicing in Numpy Arrays

# 1. Indexing

In [8]:
import numpy as np
var = np.array([9,8,7,6])
#               0,1,2,3
#               -4,-3,-2,-1
print(var[1])
print(var[-3])

8
8


In [ ]:
#----->column
#  1 2 3
#[[9 8 7] ---> zero row
# [4 5 6]] ---> first row

In [26]:
var1 = np.array([[9,8,7],[4,5,6]])
print(var1)
print()
print('Dimension:',var1.ndim)
print()
print('zero row 1st column:',var1[0,0])
print('zero row 2nd column:',var1[0,1])
print('zero row 3rd column:',var1[0,2])
print('first row 1st column:',var1[1,0])
print('first row 2nd column:',var1[1,1])
print('first row 3rd column:',var1[1,2])

[[9 8 7]
 [4 5 6]]

Dimension: 2

zero row 1st column: 9
zero row 2nd column: 8
zero row 3rd column: 7
first row 1st column: 4
first row 2nd column: 5
first row 3rd column: 6


In [60]:
var2 = np.array([[[1,2],[6,7]]])
print(var2)
print('Dimension:',var2.ndim)
print()
print(var2[0,0,0])
print(var2[0,0,1])
print(var2[0,1,0])
print(var2[0,1,1])

[[[1 2]
  [6 7]]]
Dimension: 3

1
2
6
7


# 2. Slicing

In [85]:
import numpy as np
var = np.array([1,2,3,4,5,6,7])
#               0,1,2,3,4,5,6
print(var)
print("2 to 5:- ",var[1:5]) #(start,stop)
print()
print("2 to End:- ",var[1:])
print()
print("Start to 5:- ",var[:5])
print()
print('stop:- ',var[1:5:2]) #(start , stop, step)
print('stop:- ',var[::2])

[1 2 3 4 5 6 7]
2 to 5:-  [2 3 4 5]

2 to End:-  [2 3 4 5 6 7]

Start to 5:-  [1 2 3 4 5]

stop:-  [2 4]
stop:-  [1 3 5 7]


In [87]:
# 2-D array

#------> index
#   0   1  2  3
# [[9  8  7  6] ----> row 0
#  [11 12 13 14]]----> row 1

In [91]:
var1 = np.array([[1,2,3,4,5],[9,8,7,6,5],[11,12,13,14,15]])
#                 0,1,2,3,4   0,1,2,3,4   0 ,1 ,2 ,3 ,4
#                 ---0-----   ----1-----  -----2-------
print(var1)
print()

print('8 to 5:-',var1[1,1:])

[[ 1  2  3  4  5]
 [ 9  8  7  6  5]
 [11 12 13 14 15]]

8 to 5:- [8 7 6 5]
