# Data Types in NumPy Arrays

- bool_ : Boolean (True or False) stored as a byte
- int_ : Default integer type(same as C long; normally either int64 or int32)
- intc : indentical to c int(normally int32 or int64)
- intp : integer used for indexing(same as C ssize_t; normally either int32 or int64)
- int8 : Byte(-128 to 127)
- int16 :integer(-32768 to 32767)
- int32 : integer(-2147483648 to 2147483647)
- int64 : integer(-9223372036854775808 to 9223372036854775807)
- uint8 : unsigned  integer (0 to 255)
- uint16 : unsigned integer (0 to 65535)
- uint32 : unsigned integer (0 to 4294967295)
- uint64 : unsigned integer(0 to 18446744073709551615)
- float_ : shorthand for float64
- float16 : half percision float: sign bit , 5 bits exponent , 10 bits mantissa
- float32 : single percision float:sign bit , 8 bits exponent , 23 bits for mantissa
- float64 : Double precision float : sign bit, 11 bits exponent , 52 bits for the mantissa
- complex_ : shorthand for complex128
- complex64 : complex number, represented by two 32-bit floats( real and imaginary components)
- complex128 : complex number, represented by two 64-bit floats (real and imaginary components)



## Data Type

In [13]:
import numpy as np
var = np.array([1,2,3,4,12,13,14,15])
print('Data Type :',var.dtype) 

Data Type : int32


In [15]:
var = np.array([1.0,1.2,1.3])
print('Data Type :',var.dtype)

Data Type : float64


In [17]:
var = np.array(['m','a','y','u'])
print('Data Type :',var.dtype)

Data Type : <U1


In [19]:
var = np.array(['m','a','y','u',1,2,3,4])
print('Data Type :',var.dtype)

Data Type : <U11


## list of characters that are used to represent dtype in Numpy 

- i: integer
- b: boolean
- u: unsigned integer
- f: float
- c: complex float
- m: timedelta
- M: datatime
- O: object
- S: string
- U: Unicode string
- V: the fixed chunk of memory for other types(void)

In [24]:
x= np.array([1,2,3,4])
print('Data Type :',x.dtype)

Data Type : int32


In [30]:
x= np.array([1,2,3,4],dtype=np.int8)
print('Data Type :',x.dtype)
print(x)

Data Type : int8
[1 2 3 4]


In [32]:
x1= np.array([1,2,3,4],dtype= 'f')
print('Data Type :',x1.dtype)
print(x1)

Data Type : float32
[1. 2. 3. 4.]


In [34]:
x2= np.array([1,2,3,4])
new=np.float32(x2)
print('Data Type :',x2.dtype)
print(x2)
print(new)
print('Data Type :',new.dtype)

Data Type : int32
[1 2 3 4]
[1. 2. 3. 4.]
Data Type : float32


In [38]:
x2= np.array([1,2,3,4])
new=np.float32(x2)
new_one=np.int_(new)
print('Data Type :',x2.dtype)
print(x2)
print(new)
print('Data Type :',new.dtype)
print('Data Type :',new_one.dtype)
print(new_one)

Data Type : int32
[1 2 3 4]
[1. 2. 3. 4.]
Data Type : float32
Data Type : int32
[1 2 3 4]


In [40]:
x3= np.array([1,2,3,4])
new_1 = x3.astype(float)
print(x3)
print(new_1)

[1 2 3 4]
[1. 2. 3. 4.]
