# Iterating NumPy Array

##  1-D Array

In [6]:
import numpy as np
var = np.array([9,8,7,6,5,4])
print(var)
print()
for i in var:
    print(i)
    

[9 8 7 6 5 4]

9
8
7
6
5
4


##  2-D Array

In [15]:
var1 = np.array([[1,2,3,4],[1,2,3,4]])
print(var1)
print()
for j in var1:
    print(j)
print()

for k in var1:
    for l in k:
        print(l)

[[1 2 3 4]
 [1 2 3 4]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


## 3-D array

In [23]:
var2 = np.array([[[1,2,3,4],[1,2,3,4]]])
print(var2)
print()
for j in var2:
    for m in j:
        print(m)
print()

for k in var2:
    for l in k:
        for m in l:
            print(m)

[[[1 2 3 4]
  [1 2 3 4]]]

[1 2 3 4]
[1 2 3 4]

1
2
3
4
1
2
3
4


In [37]:
var3 = np.array([[[5,6,7,8],[1,2,3,4]]])
print(var3)
print()
for j in var3:
    for m in j:
        print(m)
print()

for i in np.nditer(var3,flags=['buffered'],op_dtypes=['S']):
    print(i)

print()
for i in np.nditer(var3):
    print(i)

[[[5 6 7 8]
  [1 2 3 4]]]

[5 6 7 8]
[1 2 3 4]

b'5'
b'6'
b'7'
b'8'
b'1'
b'2'
b'3'
b'4'

5
6
7
8
1
2
3
4


In [41]:
var3 = np.array([[[5,6,7,8],[1,2,3,4]]])
print(var3)
print()

print()
for i,d in np.ndenumerate(var3): ## used for indexing :- function(ndenumerate)
    print(i,d)

[[[5 6 7 8]
  [1 2 3 4]]]


(0, 0, 0) 5
(0, 0, 1) 6
(0, 0, 2) 7
(0, 0, 3) 8
(0, 1, 0) 1
(0, 1, 1) 2
(0, 1, 2) 3
(0, 1, 3) 4
