# Shape & Reshaping in NumPy Arrays

## shape

In [9]:
import numpy as np

var=np.array([[1,2,3,4],[1,2,3,4]])
print(var)
print()
print(var.shape)

[[1 2 3 4]
 [1 2 3 4]]

(2, 4)


In [59]:
var1 = np.array([1,2,3,4],ndmin=4)
print(var1)
print()
print('Dimension:',var1.ndim)
print()
print(var1.shape)

[[[[1 2 3 4]]]]

Dimension: 4

(1, 1, 1, 4)


## Reshape

In [57]:
var2 = np.array([1,2,3,4,5,6])
print(var2)
print('Dimension:',var2.ndim)
print()
x = var2.reshape(2,3)
print(x)
print('Dimension:',x.ndim)

[1 2 3 4 5 6]
Dimension: 1

[[1 2 3]
 [4 5 6]]
Dimension: 2


In [55]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print('Dimension:',var3.ndim)
print()
x1 = var3.reshape(2,3,2)
print(x1)
print('Dimension:',x1.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension: 3


In [53]:
var3 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var3)
print('Dimension:',var3.ndim)

print()

x1 = var3.reshape(2,3,2)
print(x1)
print('Dimension:',x1.ndim)

print('reshaping....')
print()
one=x1.reshape(-1)
print(one)
print('Dimension:',one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
Dimension: 3
reshaping....

[ 1  2  3  4  5  6  7  8  9 10 11 12]
Dimension: 1
