# Creating NumPy Arrays

#### To create a NumPy array , you can use the function np.array()

In [7]:
import numpy as np
a = np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
l=[]
for i in range(1,5):
    int_1=int(input('Enter :'))
    l.append(int_1)
print(np.array(l))

Enter : 12
Enter : 13
Enter : 14
Enter : 15


[12 13 14 15]


## Dimensions in Array 
- 1-D Arrays
- 2-D Arrays
- 3-D Arrays
- Higher Dimensional Arrays

In [17]:
arr2=np.array([[1,2,3,4],[1,2,3,4]])
print(arr2)
print('dimensions=' ,arr2.ndim)

[[1 2 3 4]
 [1 2 3 4]]
dimensions= 2


In [23]:
arr3=np.array([[[1,2,3,4],[6,7,8,9]]])
print(arr3)
print('dimensions=' ,arr3.ndim)

[[[1 2 3 4]
  [6 7 8 9]]]
dimensions= 3


In [27]:
arrn=np.array([1,2,3,4],ndmin=10) #ndim for creating n dimensions
print(arrn)
print('dimensions',arrn.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]]
dimensions 10


## Special NumPy Array 
- array filled with 0's
- array filled with 1's
- create an empty array
- an array with a range of elements
- array diagonal element filled with 1's
- create a array with values that are spaced linearly in a specified interval

#### zeros

In [44]:
import numpy as np
arr_zero = np.zeros(4)
arr_zero1 = np.zeros((3,4))  # 3 rows 4 columns
print(arr_zero)
print('\n')
print(arr_zero1)

[0. 0. 0. 0.]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### ones

In [53]:
import numpy as np
arr_one = np.ones(4)
arr_one1 = np.ones((3,4))  # 3 rows 4 columns
print(arr_one)
print('\n')
print(arr_one1)

[1. 1. 1. 1.]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


#### Empty

In [56]:
arr_emp=np.empty(4)
print(arr_emp)

[1. 1. 1. 1.]


#### range

In [61]:
arr_rn= np.arange(4)
print(arr_rn)

[0 1 2 3]


#### Diagonal

In [66]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [68]:
arr_dia = np.eye(3,5)
print(arr_dia)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


#### Linspace

In [72]:
arr_lin=np.linspace(1,10,num=5)
print(arr_lin)

[ 1.    3.25  5.5   7.75 10.  ]


# Create NumPy Arrays with Random Numbers

### 1. rand()
- rand() : the function is used to generate a random number between 0 to 1

In [4]:
import numpy as np 

var = np.random.rand(4)
print(var)

[0.59144552 0.39355172 0.688822   0.65727285]


In [6]:
var1=np.random.rand(2,5)
print(var1)

[[0.18001337 0.34133453 0.56020195 0.87712259 0.83678118]
 [0.78844627 0.74536219 0.84626592 0.39463241 0.23991548]]


### 2. randn()
- randn() : the function is used to generate a random value cloase to zero.
   This may return positive or negative numbers as well.

In [12]:
var2 = np.random.randn(4)
print(var2)

[-0.90282377  0.83315867 -0.97782838 -0.20361621]


### 3. ranf()
- ranf() : the function for doing random sampling in numpy . It returns an array of specified shape and fills it with random floats in the half open interval [0.0,1.0)

In [19]:
var3=np.random.ranf(4)
print(var3)

[0.95747664 0.55213651 0.19080814 0.31665953]


### 4. randint()
- the function is used to generate a random number between a given range.

In [23]:
var4 = np.random.randint(5,20,5) #min,max,total_values
print(var4)

[ 5 19 17  9 12]
