# Arithmetic Operations in NumPy Arrays 

- a+b :   np.add(a,b)
- a-b :   np.substract(a,b)
- a*b :   np.multiply(a,b)
- a/b :   np.divide(a,b)
- a%b :   np.mod(a,b)
- a**b:   np.power(a,b)
- 1/a :   np.reciprocal(a)

# 1-D array

In [8]:
import numpy as np
var= np.array([1,2,3,4])
varadd=var + 3
print(varadd) #each number gets added by 3

[4 5 6 7]


In [10]:
import numpy as np
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])
varadd=var1 + var2
print(varadd)

[2 4 6 8]


In [20]:
import numpy as np
var1= np.array([1,2,3,4])
var2= np.array([1,2,3,4])
varadd=np.add(var1,var2)
print(varadd)

[2 4 6 8]


In [12]:
import numpy as np
var= np.array([1,2,3,4])
varadd=var - 3
print(varadd)

[-2 -1  0  1]


In [14]:
import numpy as np
var= np.array([1,2,3,4])
varadd=var * 3
print(varadd)

[ 3  6  9 12]


In [16]:
import numpy as np
var= np.array([1,2,3,4])
varadd=var / 3
print(varadd)

[0.33333333 0.66666667 1.         1.33333333]


In [18]:
import numpy as np
var= np.array([1,2,3,4])
varadd=var % 3
print(varadd)

[1 2 0 1]


In [38]:
import numpy as np
var= np.array([1,2,3,4])
varadd=np.reciprocal(var)
print(varadd)

[1 0 0 0]


# 2-D array

In [36]:
var21= np.array([[1,2,3,4],[1,2,3,4]])
var22= np.array([[1,2,3,4],[1,2,3,4]])
print(var21)
print()
print(var22)
print()
varadd2=var21*var22
print(varadd2)

[[1 2 3 4]
 [1 2 3 4]]

[[1 2 3 4]
 [1 2 3 4]]

[[ 1  4  9 16]
 [ 1  4  9 16]]


# Arithmetic Functions

- np.min(x)
- np.max(x)
- np.argmin(x)
- np.sqrt(x)
- np.sin(x)
- np.cos(x)
- np.cumsum(x)

In [66]:
import numpy as np

var=np.array([1,4,3,4,25,3,4,2])
print('maximum number:',np.max(var),np.argmin(var)) # max number, position of a number
print('minimum number:',np.min(var),np.argmax(var))
print('sqrt :',np.sqrt(var))

maximum number: 25 0
minimum number: 1 4
sqrt : [1.         2.         1.73205081 2.         5.         1.73205081
 2.         1.41421356]


In [60]:
var1 = np.array([[2,1,3],[9,5,6]])
print(np.min(var1,axis=1)) # axis =1 is for row
print(np.min(var1,axis=0)) # axis=0 is for column 

[1 5]
[2 1 3]


In [70]:
var2 = np.array([1,2,3])
print(np.sin(var2))
print(np.cos(var2))
print(np.cumsum(var2))

[0.84147098 0.90929743 0.14112001]
[ 0.54030231 -0.41614684 -0.9899925 ]
[1 3 6]
