# Join and Split Functions in Numpy Array

- Join Array :- Joining means putting contents of two or more arrays in a single array

### Join array

#### Concatenate function

In [6]:
import numpy as np

var = np.array([1,2,3,4])
var1 = np.array([9,8,7,6])

#concatenate function

ar = np.concatenate((var,var1))
print('concatenate :- ',ar)

concatenate :-  [1 2 3 4 9 8 7 6]


In [14]:
var2 = np.array([[1,2],[3,4]])
var3 = np.array([[9,8],[7,6]])

#concatenate function
print('var2 :- \n',var2)
print('var3 :- \n',var3)
ar1 = np.concatenate((var2,var3),axis=1)
ar2 = np.concatenate((var2,var3),axis=0)
print('concatenate along axis 1 :- \n',ar1)
print('concatenate along axis 0 :- \n',ar2)

var2 :- 
 [[1 2]
 [3 4]]
var3 :- 
 [[9 8]
 [7 6]]
concatenate along axis 1 :- 
 [[1 2 9 8]
 [3 4 7 6]]
concatenate along axis 0 :- 
 [[1 2]
 [3 4]
 [9 8]
 [7 6]]


### Stack Function

In [30]:
var4 = np.array([1,2,3,4])
var5 = np.array([9,8,7,6])

#concatenate function

ar3 = np.stack((var4,var5),axis=1)
ar4 = np.hstack((var4,var5)) ## row
ar5 = np.vstack((var4,var5)) ## column
ar6 = np.dstack((var4,var5)) ## height
print('stack:-\n ',ar3)
print()
print('stack by the row:-\n ',ar4)
print()
print('stack by the column:-\n ',ar5)
print()
print('stack by the height:-\n ',ar6)

stack:-
  [[1 9]
 [2 8]
 [3 7]
 [4 6]]

stack by the row:-
  [1 2 3 4 9 8 7 6]

stack by the column:-
  [[1 2 3 4]
 [9 8 7 6]]

stack by the height:-
  [[[1 9]
  [2 8]
  [3 7]
  [4 6]]]


## Split Array

- Split Array :- Splitting breaks one array into multiple 

#### How to split 1-D array?

In [50]:
import numpy as np
var = np.array([1,2,3,4,5,6])
print('var \n ',var)
ar = np.array_split(var,3)
print()
print('split array\n',ar)
print()
print('1st array:-',ar[0])
print()
print(type(ar))

var 
  [1 2 3 4 5 6]

split array
 [array([1, 2]), array([3, 4]), array([5, 6])]

1st array:- [1 2]

<class 'list'>


#### How to split 2-D array?

In [69]:
import numpy as np
var1 = np.array([[1,2],[3,4],[5,6]])
print('var1 \n ',var1)
ar1 = np.array_split(var1,2)
ar2 = np.array_split(var1,2,axis=1)
print()
print('split array\n',ar1)
print()
print('split array along axis 1\n',ar2)
print()

print(type(ar1))

var1 
  [[1 2]
 [3 4]
 [5 6]]

split array
 [array([[1, 2],
       [3, 4]]), array([[5, 6]])]

split array along axis 1
 [array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]

<class 'list'>
