# Matrix in NumPy Arrays

In [12]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
print('var\n',var)
print('Type:-',type(var))

var
 [[1 2 3]
 [1 2 3]]
Type:- <class 'numpy.matrix'>


In [14]:
var1 = np.array([[1,2,3],[1,2,3]])
print('var1\n',var1)
print('Type:-',type(var1))

var1
 [[1 2 3]
 [1 2 3]]
Type:- <class 'numpy.ndarray'>


In matrix multiplication takes places through dot product

In [32]:
import numpy as np
var = np.matrix([[1,2,3],[1,2,3]])
var2 = np.matrix([[1,2,3],[1,2,3]])

print('var\n',var)
print('var2\n',var2)
print()
print('Addition;-\n',var+var2)

var
 [[1 2 3]
 [1 2 3]]
var2
 [[1 2 3]
 [1 2 3]]

Addition;-
 [[2 4 6]
 [2 4 6]]


In [34]:
import numpy as np
var = np.matrix([[1,2],[1,2]])
var2 = np.matrix([[1,2],[1,2]])

print('var\n',var)
print('var2\n',var2)
print()
print('Addition;-\n',var+var2)
print('Multiplication;-\n',var.dot(var2))

var
 [[1 2]
 [1 2]]
var2
 [[1 2]
 [1 2]]

Addition;-
 [[2 4]
 [2 4]]
Multiplication;-
 [[3 6]
 [3 6]]


# Matrix Function in NumPy Arrays
- Transpose
- Swapaxes
- Inverse
- Power
- Determinant

## Transpose

In [49]:
import numpy as np
var = np.matrix([[1,2,3],[4,5,6]])
print('var\n',var)
print()
print('Transpose\n',np.transpose(var))
print('\n',var.T)

var
 [[1 2 3]
 [4 5 6]]

Transpose
 [[1 4]
 [2 5]
 [3 6]]

 [[1 4]
 [2 5]
 [3 6]]


## Swapaxes

In [54]:
var = np.matrix([[1,2,3],[4,5,6]])
print('var\n',var)
print('After Swapping')
print(np.swapaxes(var,0,1)) #converts 0 axis into 1 axis 

var
 [[1 2 3]
 [4 5 6]]
After Swapping
[[1 4]
 [2 5]
 [3 6]]


In [56]:
var2 = np.matrix([[1,2],[3,4]])
print('var2\n',var2)
print('After Swapping')
print(np.swapaxes(var2,0,1))

var2
 [[1 2]
 [3 4]]
After Swapping
[[1 3]
 [2 4]]


## Inverse

In [59]:
var3 = np.matrix([[1,2],[3,4]])
print('var3\n',var3)
print()
print('Inverse matrix \n')
print(np.linalg.inv(var3))

var3
 [[1 2]
 [3 4]]

Inverse matrix 

[[-2.   1. ]
 [ 1.5 -0.5]]


## Power

In [68]:
var4 = np.matrix([[1,2],[3,4]])
print('var4\n',var4)
print()
print(np.linalg.matrix_power(var4,2))
print()
print('identity Matrix')
print(np.linalg.matrix_power(var4,0))
print()
print('Inverse Matrix')
print(np.linalg.matrix_power(var4,-2))
print()

var4
 [[1 2]
 [3 4]]

[[ 7 10]
 [15 22]]

identity Matrix
[[1 0]
 [0 1]]

Inverse Matrix
[[ 5.5  -2.5 ]
 [-3.75  1.75]]



## Determinant

In [80]:
var5 = np.matrix([[1,2,3],[3,4,3],[1,4,3]])
print('var4\n',var5)
print()
print('Determinant\n')
print(np.linalg.det(var5))

var4
 [[1 2 3]
 [3 4 3]
 [1 4 3]]

Determinant

12.000000000000005
